name: Dependency and License Scan (Release)
on:
  pull_request:
    branches:
      - master
  release:
    types:
      - published
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Fetch Tags
        run: |
          git fetch --tags
      - name: Checkout latest tag
        run: |
          git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
      - name: Install Fossa CLI
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - name: Initialize Fossa
        run: |
          fossa init
      - name: Rename Fossa project
        run: |
          sed -i 's/project: .*/project: cass-operator/g' .fossa.yml
      - name: Scan for dependencies and licenses
        run: |
          FOSSA_API_KEY=${{ secrets.FOSSA_PUSH_ONLY_API_KEY }} fossa analyze -r $(git describe --tags `git rev-list --tags --max-count=1`)
